// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzV1ZD37DI4rKZCFfXNzMAuKu2nyFJLSo',
    appId: '1:201653918245:android:73072e3aa8e6fedbc3bdcc',
    messagingSenderId: '201653918245',
    projectId: 'wissme-691f6',
    databaseURL: 'https://wissme-691f6-default-rtdb.firebaseio.com',
    storageBucket: 'wissme-691f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLvmxIhvtdx6qz2SQgbQ2lwAm-2ysaEuw',
    appId: '1:201653918245:ios:aa3061a92d01280bc3bdcc',
    messagingSenderId: '201653918245',
    projectId: 'wissme-691f6',
    databaseURL: 'https://wissme-691f6-default-rtdb.firebaseio.com',
    storageBucket: 'wissme-691f6.appspot.com',
    androidClientId: '201653918245-4n10b1rsjfg008e9049dt96ialgqagos.apps.googleusercontent.com',
    iosBundleId: 'com.example.wissme',
  );
}
